export enum MotivoRechazo {
    DUPLICADA = 'DUPLICADA',
    INVALIDA = 'INVALIDA',
    FUERA_DE_ALCANCE = 'FUERA_DE_ALCANCE',
    INFORMACION_INSUFICIENTE = 'INFORMACION_INSUFICIENTE',
    PLAZO_VENCIDO = 'PLAZO_VENCIDO'
}