export enum AccionHistorial {
    REGISTRO = 'REGISTRO',
    CLASIFICACION = 'CLASIFICACION',
    ASIGNACION_RESPONSABLE = 'ASIGNACION_RESPONSABLE',
    ATENCION = 'ATENCION',
    CIERRE = 'CIERRE',
    EDICION = 'EDICION'
}