export enum TipoSolicitud {
    REGISTRO_ASIGNATURAS = 'REGISTRO_ASIGNATURAS',
    HOMOLOGACION = 'HOMOLOGACION',
    CANCELACION = 'CANCELACION',
    CUPOS = 'CUPOS',
    CONSULTA = 'CONSULTA',
    OTRO = 'OTRO'
}