module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dded49",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#84d5c5",
        "surface-container-low": "#f0f4f3",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#f3c01a",
        "on-tertiary-container": "#ffd051",
        "inverse-primary": "#84d5c5",
        "inverse-on-surface": "#edf2f1",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c1d02c",
        "tertiary-fixed": "#ffdf93",
        "outline-variant": "#bec9c5",
        "on-tertiary-fixed-variant": "#594400",
        "surface-container-highest": "#dfe3e2",
        "primary": "#004f45",
        "surface-container": "#ebefee",
        "primary-fixed": "#a0f2e1",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#444b00",
        "on-secondary": "#ffffff",
        "on-background": "#181c1c",
        "on-secondary-fixed": "#1a1d00",
        "background": "#f6faf9",
        "surface-container-high": "#e5e9e8",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#dded49",
        "surface-dim": "#d7dbda",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#241a00",
        "secondary": "#5b6300",
        "outline": "#6e7976",
        "on-primary-fixed-variant": "#005046",
        "tertiary": "#574200",
        "tertiary-container": "#745900",
        "on-primary": "#ffffff",
        "on-primary-container": "#94e5d5",
        "on-surface": "#181c1c",
        "surface-variant": "#dfe3e2",
        "primary-container": "#00695c",
        "surface-tint": "#046b5e",
        "on-secondary-container": "#616a00",
        "on-primary-fixed": "#00201b",
        "surface-bright": "#f6faf9",
        "surface": "#f6faf9",
        "on-surface-variant": "#3e4946",
        "inverse-surface": "#2c3131"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "gutter": "24px",
        "unit": "8px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "title-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}