spring.application.name=triage

# ==================== NEON - POSTGRESQL ====================
spring.datasource.url=jdbc:postgresql://ep-restless-rice-abcxe2j-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RmErY6wx4hVA
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

server.error.include-message=always

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# Groq
ia.habilitada=true
groq.api.key=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